In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/toyota.csv')
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,GT86,2016,16000,Manual,24089,Petrol,265,36.2,2.0
1,GT86,2017,15995,Manual,18615,Petrol,145,36.2,2.0
2,GT86,2015,13998,Manual,27469,Petrol,265,36.2,2.0
3,GT86,2017,18998,Manual,14736,Petrol,150,36.2,2.0
4,GT86,2017,17498,Manual,36284,Petrol,145,36.2,2.0
...,...,...,...,...,...,...,...,...,...
6733,IQ,2011,5500,Automatic,30000,Petrol,20,58.9,1.0
6734,Urban Cruiser,2011,4985,Manual,36154,Petrol,125,50.4,1.3
6735,Urban Cruiser,2012,4995,Manual,46000,Diesel,125,57.6,1.4
6736,Urban Cruiser,2011,3995,Manual,60700,Petrol,125,50.4,1.3
6737,Urban Cruiser,2011,4495,Manual,45128,Petrol,125,50.4,1.3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         6738 non-null   object
 1   year          6738 non-null   int64
 2   price         6738 non-null   int64
 3   transmission  6738 non-null   object
 4   mileage       6738 non-null   int64
 5   fuelType      6738 non-null   object
 6   tax           6738 non-null   int64
 7   mpg           6738 non-null   float64
 8   engineSize    6738 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 473.9+ KB

In [ ]:
df['model'].unique()

array([' GT86', ' Corolla', ' RAV4', ' Yaris', ' Auris', ' Aygo', ' C-HR',
       ' Prius', ' Avensis', ' Verso', ' Hilux', ' PROACE VERSO',
       ' Land Cruiser', ' Supra', ' Camry', ' Verso-S', ' IQ',
       ' Urban Cruiser'], dtype=object)

In [ ]:
df.shape

(6738, 9)

In [ ]:
df.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [ ]:
df.duplicated().sum()

39

In [ ]:
#menghapus duplikat
df = df.drop_duplicates()
df.duplicated().sum()

0

In [ ]:
nilai_tukar = 17347

df['price'] = df['price'] * nilai_tukar
df['tax'] = df['tax'] * nilai_tukar
df

<ipython-input-9-52f3025200e2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'] * nilai_tukar
<ipython-input-9-52f3025200e2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tax'] = df['tax'] * nilai_tukar

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,GT86,2016,277552000,Manual,24089,Petrol,4596955,36.2,2.0
1,GT86,2017,277465265,Manual,18615,Petrol,2515315,36.2,2.0
2,GT86,2015,242823306,Manual,27469,Petrol,4596955,36.2,2.0
3,GT86,2017,329558306,Manual,14736,Petrol,2602050,36.2,2.0
4,GT86,2017,303537806,Manual,36284,Petrol,2515315,36.2,2.0
...,...,...,...,...,...,...,...,...,...
6733,IQ,2011,95408500,Automatic,30000,Petrol,346940,58.9,1.0
6734,Urban Cruiser,2011,86474795,Manual,36154,Petrol,2168375,50.4,1.3
6735,Urban Cruiser,2012,86648265,Manual,46000,Diesel,2168375,57.6,1.4
6736,Urban Cruiser,2011,69301265,Manual,60700,Petrol,2168375,50.4,1.3
6737,Urban Cruiser,2011,77974765,Manual,45128,Petrol,2168375,50.4,1.3

In [ ]:
#Mengubah Tipe Data
from sklearn.preprocessing import LabelEncoder

m_encoder = LabelEncoder()
t_encoder = LabelEncoder()
f_encoder = LabelEncoder()

df['model'] = m_encoder.fit_transform(df['model'])
df['transmission'] = t_encoder.fit_transform(df['transmission'])
df['fuelType'] = f_encoder.fit_transform(df['fuelType'])

df

<ipython-input-10-54c2f35a190b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['model'] = m_encoder.fit_transform(df['model'])
<ipython-input-10-54c2f35a190b>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transmission'] = t_encoder.fit_transform(df['transmission'])
<ipython-input-10-54c2f35a190b>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fuelType'] = f_encoder.fit_transform(df['fuelType'])

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,6,2016,277552000,1,24089,3,4596955,36.2,2.0
1,6,2017,277465265,1,18615,3,2515315,36.2,2.0
2,6,2015,242823306,1,27469,3,4596955,36.2,2.0
3,6,2017,329558306,1,14736,3,2602050,36.2,2.0
4,6,2017,303537806,1,36284,3,2515315,36.2,2.0
...,...,...,...,...,...,...,...,...,...
6733,8,2011,95408500,0,30000,3,346940,58.9,1.0
6734,14,2011,86474795,1,36154,3,2168375,50.4,1.3
6735,14,2012,86648265,1,46000,0,2168375,57.6,1.4
6736,14,2011,69301265,1,60700,3,2168375,50.4,1.3
6737,14,2011,77974765,1,45128,3,2168375,50.4,1.3

## **Preparation Data**

In [ ]:
features = ['model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg', 'engineSize']

X = df[features]
y = df['price']

X.shape, y.shape

((6699, 8), (6699,))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

**Training Data With Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)

In [ ]:
score = lr.score(X_test, y_test)
print("Akurasi Model Linear Regression : ", score)

Akurasi Model Linear Regression :  0.7909694669634745

In [ ]:
input_data = {
    'model' : 'Corolla',
    'year'  : 2015,
    'transmission' : 'Manual',
    'mileage' : 36154,
    'fuelType' : 'Petrol',
    'tax' : 5000000,
    'mpg' : 40,
    'engineSize' : 1.5

}

input_data['model'] = m_encoder.fit_transform([input_data['model']])[0]
input_data['transmission'] = t_encoder.fit_transform([input_data['transmission']])[0]
input_data['fuelType'] = f_encoder.fit_transform([input_data['fuelType']])[0]
input_df = pd.DataFrame([input_data])
input_df

   model  year  transmission  mileage  fuelType      tax  mpg  engineSize
0      0  2015             0    36154         0  5000000   40         1.5

In [ ]:
prediksi = lr.predict(input_df)
format_prediksi = round(prediksi[0], 2)

print('Harga mobil dengan model Corolla adalah : Rp.', format_prediksi)

Harga mobil dengan model Corolla adalah : Rp. 193890216.17